float32  m1P
float32  m1I
float32  m1D
uint32  m1Qpps
int32   currentM1Speed
float32  m1MotorCurrent
uint32  encoderM1value
uint8  encoderM1Status

float32  m2P
float32  m2I
float32  m2D
uint32  m2Qpps
int32   currentM2Speed
float32  m2MotorCurrent
uint32  encoderM2value
uint8  encoderM2Status

float32  mainBatteryVoltage
float32  logicBatteryVoltage
float32  temperature
uint8  stickyErrorStatus
uint8  errorStatus
string  errorString

